package com.tala.enterprise.talabank.model.db;
// Generated Oct 19, 2016 12:32:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private AccountType accountType;
     private Branch branch;
     private String accountName;
     private String accountNumber;
     private int accountBalance;
     private Date dateTime;
     private Set transactions = new HashSet(0);

    public Account() {
    }

	
    public Account(AccountType accountType, Branch branch, String accountName, String accountNumber, int accountBalance, Date dateTime) {
        this.accountType = accountType;
        this.branch = branch;
        this.accountName = accountName;
        this.accountNumber = accountNumber;
        this.accountBalance = accountBalance;
        this.dateTime = dateTime;
    }
    public Account(AccountType accountType, Branch branch, String accountName, String accountNumber, int accountBalance, Date dateTime, Set transactions) {
       this.accountType = accountType;
       this.branch = branch;
       this.accountName = accountName;
       this.accountNumber = accountNumber;
       this.accountBalance = accountBalance;
       this.dateTime = dateTime;
       this.transactions = transactions;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public AccountType getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public int getAccountBalance() {
        return this.accountBalance;
    }
    
    public void setAccountBalance(int accountBalance) {
        this.accountBalance = accountBalance;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


