package com.tala.enterprise.talabank.model.db;
// Generated Oct 19, 2016 12:32:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AccountType generated by hbm2java
 */
public class AccountType  implements java.io.Serializable {


     private Integer accountTypeId;
     private String type;
     private String description;
     private Set accounts = new HashSet(0);

    public AccountType() {
    }

	
    public AccountType(String type, String description) {
        this.type = type;
        this.description = description;
    }
    public AccountType(String type, String description, Set accounts) {
       this.type = type;
       this.description = description;
       this.accounts = accounts;
    }
   
    public Integer getAccountTypeId() {
        return this.accountTypeId;
    }
    
    public void setAccountTypeId(Integer accountTypeId) {
        this.accountTypeId = accountTypeId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


