package com.tala.enterprise.talabank.model.db;
// Generated Oct 19, 2016 12:32:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer branchId;
     private String branchName;
     private String branchLocation;
     private Set accounts = new HashSet(0);

    public Branch() {
    }

	
    public Branch(String branchName, String branchLocation) {
        this.branchName = branchName;
        this.branchLocation = branchLocation;
    }
    public Branch(String branchName, String branchLocation, Set accounts) {
       this.branchName = branchName;
       this.branchLocation = branchLocation;
       this.accounts = accounts;
    }
   
    public Integer getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getBranchLocation() {
        return this.branchLocation;
    }
    
    public void setBranchLocation(String branchLocation) {
        this.branchLocation = branchLocation;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


