package com.tala.enterprise.talabank.model.db;
// Generated Oct 19, 2016 12:32:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private Integer transactionTypeId;
     private String type;
     private String description;
     private Set transactions = new HashSet(0);

    public TransactionType() {
    }

	
    public TransactionType(String type, String description) {
        this.type = type;
        this.description = description;
    }
    public TransactionType(String type, String description, Set transactions) {
       this.type = type;
       this.description = description;
       this.transactions = transactions;
    }
   
    public Integer getTransactionTypeId() {
        return this.transactionTypeId;
    }
    
    public void setTransactionTypeId(Integer transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


